"""Write cycle notes, lessons, and escalations into an Obsidian vault folder.

This is the local on-disk side of the obsidian vault integration from the
content-orchestrator skill (Section 8). The live MCP/REST path is wired later
via Hermes config; this module gives the scheduler and Hermes a durable file-based
fallback so escalations and cycle notes land in the vault even before Hermes is
connected to the vault.
"""

import json
import os
import sqlite3
from datetime import datetime, date
from pathlib import Path

VAULT_ENV = "VILLAGE_OBSIDIAN_VAULT_PATH"
DEFAULT_VAULT_REL = "~/Obsidian/Ecosystem"


def vault_root() -> Path:
    raw = os.environ.get(VAULT_ENV)
    if raw:
        return Path(raw).expanduser().resolve()
    return Path(DEFAULT_VAULT_REL).expanduser().resolve()


def ensure_structure() -> dict:
    root = vault_root()
    subfolders = [
        "Cycles",
        "Niches",
        "Analytics",
        "Lessons",
        "Escalations",
    ]
    paths = {}
    for sub in subfolders:
        p = root / sub
        p.mkdir(parents=True, exist_ok=True)
        paths[sub] = p
    return paths


def cycle_note_path(date_str: str, job_id: str) -> Path:
    root = vault_root()
    return root / "Cycles" / f"{date_str}-{job_id}.md"


def write_cycle_note(conn, resident_id, resident_name, cycle: int, decision: str,
                     reasoning: str, delegated_tasks: list, budget_used: float,
                     escalations: list, job_id: str) -> Path:
    """Append a cycle note following the template in the orchestrator skill."""
    paths = ensure_structure()
    today = date.today().isoformat()
    path = cycle_note_path(today, job_id)
    resident_row = conn.execute(
        "SELECT id, zone, niche, format, proven FROM residents WHERE id = ?", (resident_id,)
    ).fetchone()
    fmt = resident_row["format"] if resident_row else "[]"
    try:
        fmt_list = json.loads(fmt) if fmt else []
    except (json.JSONDecodeError, TypeError):
        fmt_list = []
    lines = [
        f"# Cycle {cycle} — {resident_name}",
        "",
        f"**Date:** {today}",
        f"**Niche:** {resident_name}",
        f"**Zone:** {resident_row['zone'] if resident_row else 'gray'}",
        f"**Format (this cycle):** {', '.join(fmt_list) or 'unspecified'}",
        f"**Proven-profitable (human-marked):** {'yes' if resident_row and resident_row['proven'] else 'no'}",
        "",
        "## Decision",
        "",
        decision,
        "",
        "## Reasoning",
        "",
        reasoning,
        "",
        "## Delegated tasks",
        "",
    ]
    if delegated_tasks:
        for t in delegated_tasks:
            lines.append(f"- **{t.get('agent')}** — {t.get('task')}")
            spec = t.get('spec')
            if spec:
                lines.append(f"  ```json")
                lines.append(json.dumps(spec, indent=2))
                lines.append(f"  ```")
    else:
        lines.append("(none this cycle)")
    lines += [
        "",
        "## Budget used this cycle",
        "",
        f"${budget_used:.2f}",
        "",
        "## Escalations",
        "",
    ]
    if escalations:
        for e in escalations:
            lines.append(f"- {e}")
    else:
        lines.append("(none this cycle)")
    lines += [
        "",
        "## Outcome",
        "",
        "(to be filled after worker outputs are reviewed)",
        "",
        "## Lessons",
        "",
        "(any new Lessons entries get their own file in Lessons/ and are referenced here)",
        "",
        "---",
        f"auto-generated by Village scheduler | {datetime.now().isoformat()}",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_lesson_entry(title: str, body: str, niche: str = "") -> Path:
    """Append a specific lesson to Lessons/<title-slug>.md — short and specific,
    not rewritten, so reasoning compounds across cycles."""
    paths = ensure_structure()
    slug = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in title.lower()).strip("-_")
    path = paths["Lessons"] / f"{slug}.md"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    entry = [
        f"## {title}",
        "",
        body.strip(),
        "",
        f"---",
        f"added {datetime.now().isoformat()}",
        "",
    ]
    # If the file exists and has this heading already, append a new sub-entry
    # rather than duplicating the heading.
    if title in existing:
        insert = [
            f"### update {datetime.now().isoformat()}",
            "",
            body.strip(),
            "",
        ]
        # Insert after the existing heading block.
        idx = existing.find(f"## {title}")
        if idx != -1:
            end = existing.find("\n## ", idx + 1)
            if end == -1:
                end = len(existing)
            new_text = existing[:end] + "\n".join(insert) + existing[end:]
            path.write_text(new_text, encoding="utf-8")
            return path
    # New file or new heading.
    heading = f"# Lessons — {niche or 'general'}\n" if not existing else ""
    path.write_text(heading + "\n".join(entry), encoding="utf-8")
    return path


def write_escalation(conn, resident_id, resident_name, kind, title, body) -> Path:
    """Mirror an escalation into Ecosystem/Escalations/ so it is visible in Obsidian
    even after the Discord/email notification scrolls away."""
    paths = ensure_structure()
    today = date.today().isoformat()
    slug = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in title.lower()).strip("-_")
    path = paths["Escalations"] / f"{today}-{slug}.md"
    resident_row = conn.execute(
        "SELECT id, zone, niche, proven FROM residents WHERE id = ?", (resident_id,)
    ).fetchone()
    lines = [
        f"# Escalation: {title}",
        "",
        f"**Date:** {today}",
        f"**Resident / niche:** {resident_name or 'unassigned'}",
        f"**Kind:** {kind}",
        f"**Status:** pending",
        "",
        "## Body",
        "",
        body.strip(),
        "",
        "## Resolution",
        "",
        "(approved / denied / resolved — to be filled by the human)",
        "",
        "---",
        f"auto-generated by Village scheduler | {datetime.now().isoformat()}",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_analytics_raw(conn, resident_id, resident_name, raw_metrics: dict) -> Path:
    """Dump raw pulled metrics from OPENCODE-ANALYST into Ecosystem/Analytics/."""
    paths = ensure_structure()
    today = date.today().isoformat()
    slug = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in resident_name.lower()).strip("-_")
    path = paths["Analytics"] / f"{today}-{slug}.json"
    payload = {
        "timestamp": datetime.now().isoformat(),
        "resident": resident_name,
        "resident_id": resident_id,
        "metrics": raw_metrics,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def list_escalations() -> list:
    """Return all pending escalations as dicts, for the dashboard and Hermes."""
    root = vault_root()
    esc_dir = root / "Escalations"
    if not esc_dir.is_dir():
        return []
    out = []
    for path in sorted(esc_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        status = "pending"
        for line in text.splitlines():
            if line.startswith("**Status:**"):
                status = line.split(":", 1)[1].strip()
                break
        out.append({
            "path": str(path),
            "title": path.stem.split("-", 1)[-1] if "-" in path.stem else path.stem,
            "status": status,
            "text": text,
        })
    return out
